blank_issues_enabled: false
contact_links:
  - name: Box Developer Forums
    url: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
  - name: API documentation
    url: https://developer.box.com/docs
